### ISSUE TITLE
Concordion 1.4.6 incompatible with JUnit 4.12

### ISSUE THREAD

**Issue by wjbakker** [concordion/concordion#100]
Concordion 1.4.6 fails to initialize the concordion runner when used in combination with junit 4.12:

```
java.lang.Exception: Failed to initialize ConcordionRunner
    at org.junit.runners.model.InitializationError.<init>(InitializationError.java:38)
    at org.concordion.integration.junit4.ConcordionRunner.<init>(ConcordionRunner.java:52)
```

This is caused by a change in the implementation of FrameworkMethod in JUnit, that now throws a NullPointerException if its argument is null. The ConcordionRunner always creates a FrameworkMethod with null argument.

Concordion 1.4.6:

```java
    public ConcordionRunner(Class<?> fixtureClass) throws InitializationError {
        super(fixtureClass);
        (...)
        fakeMethod = new FakeFrameworkMethod();
        (...)
    }
    
    static class FakeFrameworkMethod extends FrameworkMethod {
        public FakeFrameworkMethod() {
            super(null);
        }
        (...)
    }
```

JUnit 4.11

```java
    public FrameworkMethod(Method method) {
        fMethod = method;
    }
```

JUnit 4.12:

```java
    public FrameworkMethod(Method method) {
        if (method == null) {
            throw new NullPointerException(
                    "FrameworkMethod cannot be created without an underlying method.");
        }
        this.method = method;
    }
```

**Comment by nigelcharman** [comment]
Thanks for the detailed bug report. We'll look to get a minor release out in about a week with a fix.

**Comment by calen-legaspi** [comment]
Ran into the same problem. 

Thank you, @wjbakker , for reporting!
