### ISSUE TITLE
Adding resources: "URI is not hierarchical"

### ISSUE THREAD

**Issue by dsaborg-waya** [concordion/concordion#285]
I tried to add Bootstrap to my Concordion fixture as such:

@ConcordionResources("bootstrap/bootstrap.min.css")

Where bootstrap.min.css resides in the "bootstrap" subfolder relative to the spec Java file.

Upon attempting to run my spec I get the following error message:

```
java.lang.IllegalArgumentException: URI is not hierarchical

	at java.base/java.io.File.<init>(File.java:418)
	at org.concordion.internal.FixtureType.getClassPathRoots(FixtureType.java:106)
	at org.concordion.internal.ResourceFinder.getResourcesToCopy(ResourceFinder.java:36)
	at org.concordion.internal.ConcordionBuilder.withResources(ConcordionBuilder.java:460)
	at org.concordion.internal.ConcordionBuilder.withFixture(ConcordionBuilder.java:421)
	at org.concordion.internal.FixtureRunner.<init>(FixtureRunner.java:18)
	at org.concordion.integration.junit4.ConcordionRunner.<init>(ConcordionRunner.java:62)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488)
	at org.junit.internal.builders.AnnotatedBuilder.buildRunner(AnnotatedBuilder.java:104)
	at org.junit.internal.builders.AnnotatedBuilder.runnerForClass(AnnotatedBuilder.java:86)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:26)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.requests.ClassRequest.getRunner(ClassRequest.java:33)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:49)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
```

This happens whether I run the spec directly in IntelliJ or in Gradle.

Environment:

Java 10
Concordion 2.2.0

**Comment by nigelcharman** [comment]
That works OK for me, with the `bootstrap` subfolder under the `src/test/resources` folder in a location relative to the location of the fixture file.

Would you check the location of your resources folder in your build.gradle file? If still failing, can you post a sample project that demonstrates this please?

**Comment by dsaborgink** [comment]
> That works OK for me, with the `bootstrap` subfolder under the `src/test/resources` folder in a location relative to the location of the fixture file.
> 
> Would you check the location of your resources folder in your build.gradle file? If still failing, can you post a sample project that demonstrates this please?

It's a standard Java Gradle project, so it's using the standard resources folder location.

I'm thinking this is a Java 10 issue, have you tried it on Java 10?

**Comment by nigelcharman** [comment]
Yes, I ran it in IDEA using OpenJDK 10.0.2.

I have seen this before when using jar files. Just checking you have the CSS file in that location rather than a jar or zip file?

**Comment by dsaborgink** [comment]
I'll see if I can put together a sample project demonstrating the issue.

**Comment by LukeSP** [comment]
I have also come across this issue when trying to load a image resource into my documentation. The difference for me being that the project is building with java 11. When i revert to Java8, the resource is found correctly.

**Comment by nigelcharman** [comment]
Hey @LukeSP, I've had a look but can't reproduce this. Are you able to provide a repeatable example of it?

**Comment by BittnerBarnabas** [comment]
I was able to reproduce the issue. You can run to see it failing in the attached project:
`./gradlew :test --tests "MyConcordionFixture"`
[concordion_bug.zip](https://github.com/concordion/concordion/files/5647539/concordion_bug.zip)

It seems the problem was introduced with the [multi-release jars](https://openjdk.java.net/jeps/238) in Java 9. The same issue was affecting [Liquibase](https://github.com/liquibase/liquibase/pull/830/commits/42477016a15c4255b844107262c730544a1da517) as well, they fixed it by ignoring the resource which was pointing into a multi-release jar's root. 

In the following snippet the `resources.nextElement()` points into the jar file `jar:file:/path/to/jar/jaxb-api-2.3.1.jar!/META-INF/versions/9/` 
```java
Enumeration<URL> resources;
try {
  resources = getFixtureClass().getClassLoader().getResources("");

  while (resources.hasMoreElements()) {
          rootPaths.add(new File(resources.nextElement().toExternalForm()));
      }
} catch (IOException e) {
  throw new RuntimeException("Unable to get root path", e);
} catch (URISyntaxException e) {
  throw new RuntimeException("Unable to get root path", e);
}
```

I see 2 possible fixes for this, either ignoring the `URISyntaxException` that's being thrown or instead of `resources.nextElement().toUri()` it could call `resources.nextElement().toExternalForm()` in which case the root of the multi release jar would be included in the root paths, which is most likely not desired.

**Comment by nigelcharman** [comment]
Thanks for creating the reproducible test case and analysis of the issue.

This feature is due for a refresh - now the minimum JDK is 8.0 it should 
be easier to load resources from jar files. I'll hopefully get some time 
to do this soon...
