### ISSUE TITLE
ZipException is thrown during project build process

### ISSUE THREAD

**Issue by alex-d-bondarev** [concordion/concordion#294]
Need updating `distributionUrl` in `gradle-wrapper.properties` to refer `https` instead of `http`.
This is caused by [gradle decommissioning HTTP](https://blog.gradle.org/decommissioning-http).
As a result the following exception is thrown during project build:
```bash
> ./gradlew tasks 
Unzipping /Users/user/gradle_cache/.gradle/wrapper/dists/gradle-4.7-bin/ws20r6gmsre3imjoq194k3yy/gradle-4.7-bin.zip to /Users/user/gradle_cache/.gradle/wrapper/dists/gradle-4.7-bin/ws20r6gmsre3imjoq194k3yy
Exception in thread "main" java.util.zip.ZipException: zip file is empty
        at java.util.zip.ZipFile.open(Native Method)
        at java.util.zip.ZipFile.<init>(ZipFile.java:221)
        at java.util.zip.ZipFile.<init>(ZipFile.java:151)
        at java.util.zip.ZipFile.<init>(ZipFile.java:165)
        at org.gradle.wrapper.Install.unzip(Install.java:215)
        at org.gradle.wrapper.Install.access$600(Install.java:27)
        at org.gradle.wrapper.Install$1.call(Install.java:75)
        at org.gradle.wrapper.Install$1.call(Install.java:48)
        at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:69)
        at org.gradle.wrapper.Install.createDist(Install.java:48)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:107)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
```

**Comment by nigelcharman** [comment]
Fixed by #295. Thanks Alex!
