### ISSUE TITLE
Unable to access XML parser under Java 20

### ISSUE THREAD

**Issue by talios** [concordion/concordion#347]
I'm finally updating a concordion project from Java 8 to Java 20, and notice I can't read/access the internal `SAXParser` via no.xom.Builder.

Is there a way to easily replace / work around this beyond adding '--add-opens java.xml/com.sun.org.apache.xerces.internal.parsers=ALL-UNNAMED` to my test process?

```
java.lang.IllegalAccessError: superclass access check failed: class nu.xom.JDK15XML1_0Parser (in unnamed module @0x75437611) cannot access class com.sun.org.apache.xerces.internal.parsers.SAXParser (in module java.xml) because module java.xml does not export com.sun.org.apache.xerces.internal.parsers to unnamed module @0x75437611
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1013)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:862)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:760)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:681)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:639)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:391)
	at java.base/java.lang.Class.forName(Class.java:382)
	at nu.xom.Builder.findParser(Unknown Source)
	at nu.xom.Builder.<init>(Unknown Source)
	at nu.xom.Builder.<init>(Unknown Source)
	at org.concordion.internal.XMLParser.parse(XMLParser.java:19)
	at org.concordion.internal.XMLSpecificationReader.readSpecification(XMLSpecificationReader.java:31)
	at org.concordion.Concordion.loadSpecificationFromResource(Concordion.java:104)
	at org.concordion.Concordion.getSpecification(Concordion.java:71)
	at org.concordion.Concordion.process(Concordion.java:65)
	at nz.co.smx.smx3.SpecificationTest.specification(SpecificationTest.java:108)
```

**Comment by nigelcharman** [comment]
Any joy with this yet? I'm waiting for Gradle 8.2 before running on Java 20. Does it have the same issue with Java 17? 

I'm not sure why you'd be seeing this with your runner when it's working with the default runner?

**Comment by talios** [comment]
Yep! In the end I had to add two `--add-opens` to my `maven-exec-plugin` task:

```
<argument>--add-opens</argument>
<argument>java.xml/com.sun.org.apache.xerces.internal.parsers=ALL-UNNAMED</argument>
<argument>--add-opens</argument>
<argument>java.xml/com.sun.org.apache.xerces.internal.util=ALL-UNNAMED</argument>
```

but works a treat.  Maybe it's because I'm running from a standalone project (don't ask ;p  I'm also still bootstrapping it from a custom TestNG launcher).

**Comment by nigelcharman** [comment]
Ahh, you didn't mention Maven. I think that's where your problems started 😉
